/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Zaposleni;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import konstante.Konstante;
import transfer.TransferObject;

/**
 *
 * @author Vladan
 */
public class DodajNovogZaposlenogPanel extends javax.swing.JPanel {
    private GlavnaForma glavna;
    TransferObject toZahtev = new TransferObject();
    TransferObject toOdgovor = new TransferObject();

    /**
     * Creates new form DodajNoviUgovorPanel1
     */
    public DodajNovogZaposlenogPanel(GlavnaForma g) {
        initComponents();
        this.glavna = g;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldStrucnaSprema = new javax.swing.JTextField();
        jTextFieldRadnoIskutvo = new javax.swing.JTextField();

        jButton1.setText("Dodaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ime i prezime");

        jLabel2.setText("Stručna sprema");

        jLabel3.setText("Godine radnog iskustva");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(61, 61, 61)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIme)
                            .addComponent(jTextFieldRadnoIskutvo)
                            .addComponent(jTextFieldStrucnaSprema))))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldStrucnaSprema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldRadnoIskutvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!validacija()) return;
        String imePrezime = jTextFieldIme.getText().trim();
        String strucnaSprema = jTextFieldStrucnaSprema.getText().trim();
        int godine = Integer.parseInt(jTextFieldRadnoIskutvo.getText().trim());
        try {
            
        Zaposleni z = new Zaposleni(0, imePrezime, strucnaSprema, godine);
        
        toZahtev.setOperacija(Konstante.SACUVAJ_ZAPOSLENOG);
        toZahtev.setParametar(z);
        
            Komunikacija.getInstance().posalji(toZahtev);
            toOdgovor = Komunikacija.getInstance().procitaj();
            if (!toOdgovor.getPoruka().equals("")){
                JOptionPane.showMessageDialog(this, toOdgovor.getPoruka());
                return;
            }
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio novog zaposlenog!", "Unos zaposlenog", JOptionPane.INFORMATION_MESSAGE);
            reset();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem nije u mogucnosti da sacuva novog zaposlenog!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldRadnoIskutvo;
    private javax.swing.JTextField jTextFieldStrucnaSprema;
    // End of variables declaration//GEN-END:variables

    private void reset(){
        jTextFieldIme.setText("");
        jTextFieldRadnoIskutvo.setText("");
        jTextFieldStrucnaSprema.setText("");
    }
    
    private boolean validacija(){
        boolean val ;
        String ime = jTextFieldIme.getText().trim();
        String strucnaSprema = jTextFieldStrucnaSprema.getText().trim();
        String radnoIskustvoStr = jTextFieldRadnoIskutvo.getText().trim();
        
        int imeInt;
        int strucnaSpremaInt;
        int radnoIskustvo;
        
        if(ime.equals("") || strucnaSprema.equals("") || radnoIskustvoStr.equals("")){
            JOptionPane.showMessageDialog(this, "Popunite sva polja","Greška",JOptionPane.ERROR_MESSAGE);
            val = false;
            return val;
        }
        try {
            imeInt = Integer.parseInt(ime);
            JOptionPane.showMessageDialog(this, "Ime zaposlenog ne sme biti broj","Greška",JOptionPane.ERROR_MESSAGE);
            val = false;
            return val;
        } catch (Exception e) {
            val = true;
        }
        try {
            strucnaSpremaInt = Integer.parseInt(strucnaSprema);
            JOptionPane.showMessageDialog(this, "Strucna sprema zaposlenog ne sme biti broj","Greška",JOptionPane.ERROR_MESSAGE);
            val = false;
            return val;
        } catch (Exception e) {
            val = true;
        }
        try {
            radnoIskustvo = Integer.parseInt(radnoIskustvoStr);
            val = true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Radno iskustvo se mora uneti kao broj","Greška",JOptionPane.ERROR_MESSAGE);
            val = false;
            return val;
        }
        
        return val;
        
        
    }
}
