/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Zaposleni;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import konstante.Konstante;
import transfer.TransferObject;
import util.AktivanPanel;

/**
 *
 * @author Vladan
 */
public class IzmeniZaposlenogPanel extends javax.swing.JPanel {
    TransferObject toZahtev = new TransferObject();
    TransferObject toOdgovor = new TransferObject();
    Zaposleni zaposleni;
    GlavnaForma glavna;
    /**
     * Creates new form DetaljiUgovoraPanel
     */
    public IzmeniZaposlenogPanel(Zaposleni z, GlavnaForma glavnaForma) {
        initComponents();
        glavna = glavnaForma;
        zaposleni = z;
        jTextFieldIme.setText(z.getImeIPrezime());
        jTextFieldRadnoIskutvo.setText(String.valueOf(z.getRadniStaz()));
        jTextFieldStrucnaSprema.setText(z.getStrucnaSprema());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldStrucnaSprema = new javax.swing.JTextField();
        jTextFieldRadnoIskutvo = new javax.swing.JTextField();
        jButtonIzmeni = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jLabel1.setText("Ime i prezime");

        jLabel2.setText("Stručna sprema");

        jLabel3.setText("Godine radnog iskustva");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                        .addGap(61, 61, 61)
                        .addComponent(jButtonOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIme)
                            .addComponent(jTextFieldRadnoIskutvo)
                            .addComponent(jTextFieldStrucnaSprema))))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldStrucnaSprema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldRadnoIskutvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOdustani)
                    .addComponent(jButtonIzmeni))
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        // TODO add your handling code here:
       zaposleni.setImeIPrezime(jTextFieldIme.getText().trim());
       zaposleni.setStrucnaSprema(jTextFieldStrucnaSprema.getText().trim());
       zaposleni.setRadniStaz(Integer.parseInt(jTextFieldRadnoIskutvo.getText().trim()));
       
       toZahtev.setOperacija(Konstante.IZMENI_ZAPOSLENOG);
       toZahtev.setParametar(zaposleni);
        try {
            Komunikacija.getInstance().posalji(toZahtev);
            toOdgovor = Komunikacija.getInstance().procitaj();
        } catch (IOException ex) {
            Logger.getLogger(IzmeniZaposlenogPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IzmeniZaposlenogPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!toOdgovor.getPoruka().equals("")) {
            JOptionPane.showMessageDialog(this, "Došlo je do greške, sistem ne može da zabeleži promenu", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this, "Sistem je zapamtio zaposlenog!","Info",JOptionPane.INFORMATION_MESSAGE);
        glavna.zameniAktivniPanel(AktivanPanel.PRETRAGA_ZAPOSLENOG);
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        // TODO add your handling code here:
        glavna.zameniAktivniPanel(AktivanPanel.PRETRAGA_ZAPOSLENOG);
    }//GEN-LAST:event_jButtonOdustaniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldRadnoIskutvo;
    private javax.swing.JTextField jTextFieldStrucnaSprema;
    // End of variables declaration//GEN-END:variables
}
