/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.RadneSmene;
import domen.Zaposleni;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import konstante.Konstante;
import logovanje.Logovanje;
import transfer.TransferObject;
import util.AktivanPanel;

/**
 *
 * @author Vladan
 */
public class IzmeniRadnuSmenuPanel extends javax.swing.JPanel {
    TransferObject toZahtev = new TransferObject();
    TransferObject toOdgovor = new TransferObject();
    RadneSmene smena;
    GlavnaForma glavna;

    /**
     * Creates new form IzmeniRadnuSmenuPanel
     */
    public IzmeniRadnuSmenuPanel(RadneSmene s, GlavnaForma g) {
        initComponents();
        smena = s;
        glavna = g;
        srediKombo();
        pocetno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jTextFieldSmena = new javax.swing.JTextField();
        jComboBoxZaposleni = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Zaposleni:");

        jLabel2.setText("Datum:");

        jLabel3.setText("Vreme/smena:");

        jComboBoxZaposleni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Izmeni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Odustani");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)
                        .addComponent(jTextFieldSmena, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(41, 41, 41)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSmena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        glavna.zameniAktivniPanel(AktivanPanel.PRETRAGA_RASPOREDA);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(!validacija()) return;
        
        //ovde sam samo datum proveravao, ostalo je u validaciji
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date datum;
        try {
            datum = sdf.parse(jTextFieldDatum.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Datum mora biti u obliku dd/MM/yyyy");
            return;
        }
        
        int vreme = Integer.parseInt(jTextFieldSmena.getText().trim());
        Zaposleni z = (Zaposleni) jComboBoxZaposleni.getSelectedItem();
        
        
        smena.setDatumRadneSmene(datum);
        smena.setZaposleni(z);
        smena.setVremeRadneSmene(vreme);
        smena.setKoordinatorID(Logovanje.getInstance().getUlogovaniKoordinator());
        
        
        toZahtev.setOperacija(Konstante.IZMENI_RADNUSMENU);
        toZahtev.setParametar(smena);
        try {
            Komunikacija.getInstance().posalji(toZahtev);
            toOdgovor = Komunikacija.getInstance().procitaj();
        } catch (IOException ex) {
            Logger.getLogger(IzmeniRadnuSmenuPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IzmeniRadnuSmenuPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!toOdgovor.getPoruka().equals("")) {
            JOptionPane.showMessageDialog(this, toOdgovor.getPoruka(), "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Sistem je uspešno sačuvao radnu smenu!","Info",JOptionPane.INFORMATION_MESSAGE);
        glavna.zameniAktivniPanel(AktivanPanel.PRETRAGA_RASPOREDA);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldSmena;
    // End of variables declaration//GEN-END:variables

    private void pocetno(){
       // jComboBoxZaposleni.setSelectedItem(smena.getZaposleni());
        SimpleDateFormat sdf  = new SimpleDateFormat("dd/MM/yyyy");
        String datum = sdf.format(smena.getDatumRadneSmene());
        jTextFieldDatum.setText(datum);
        jTextFieldSmena.setText(String.valueOf(smena.getVremeRadneSmene()));
    }
    
    private void srediKombo(){
        toZahtev.setOperacija(Konstante.VRATI_ZAPOSLENE);
        try {
            Komunikacija.getInstance().posalji(toZahtev);
            toOdgovor = Komunikacija.getInstance().procitaj();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        if (!toOdgovor.getPoruka().equals("")) {
            JOptionPane.showMessageDialog(this, toOdgovor.getPoruka(), "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        List<Zaposleni> lista = (List<Zaposleni>) toOdgovor.getOdgovor();
        jComboBoxZaposleni.removeAllItems();
        for(Zaposleni z : lista){
                jComboBoxZaposleni.addItem(z);
                if(smena.getZaposleni().equals(z))
                    jComboBoxZaposleni.setSelectedItem(z);
            
        }
    }
    
    private boolean  validacija(){
        String smenaString = jTextFieldSmena.getText().trim();
        String datumString= jTextFieldDatum.getText().trim();
        if(smenaString.equals("") || datumString.equals("")) return false;
        int smenaInt;
        try {
            smenaInt = Integer.parseInt(smenaString);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Smena se unosi kao 1,2 ili 3", "Greška", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(smenaInt<1 || smenaInt>3){
            JOptionPane.showMessageDialog(this, "Smena se unosi kao 1,2 ili 3", "Greška", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

}
