/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import com.mysql.jdbc.StringUtils;
import domen.Koordinator;
import java.awt.Color;
import java.net.ConnectException;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import komunikacija.Komunikacija;
import konstante.Konstante;
import logovanje.Logovanje;
import transfer.TransferObject;

/**
 *
 * @author Vladan
 */
public class LogIn extends javax.swing.JFrame {
    TransferObject toZahtev = new TransferObject();
    TransferObject toOdgovor = new TransferObject();

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonUlogujSe = new javax.swing.JButton();
        jButtonOtkazi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldKorisnickoIme = new javax.swing.JTextField();
        jTextFieldSifra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButtonUlogujSe.setText("Uloguj se");
        jButtonUlogujSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUlogujSeActionPerformed(evt);
            }
        });

        jButtonOtkazi.setText("Otkazi");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });

        jLabel1.setText("Korisnicko ime:");

        jLabel2.setText("Sifra:");

        jTextFieldSifra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSifraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jButtonUlogujSe)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOtkazi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldSifra)
                            .addComponent(jTextFieldKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUlogujSe)
                    .addComponent(jButtonOtkazi))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUlogujSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUlogujSeActionPerformed
        // TODO add your handling code here:
        try {
            pokreniAplikaciju();
        } catch (ConnectException ce) {
            JOptionPane.showMessageDialog(null, "Server još uvek nije pokrenut.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonUlogujSeActionPerformed

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
        // TODO add your handling code here:
        try {
            if (Logovanje.getInstance().getUlogovaniKoordinator()== null) {
                toZahtev.setOperacija(Konstante.KRAJ_RADA);
                Komunikacija.getInstance().posalji(toZahtev);
                toOdgovor = Komunikacija.getInstance().procitaj();
                if (!toOdgovor.getPoruka().equals("")) {
                    JOptionPane.showMessageDialog(this, toOdgovor.getPoruka(), "Greška", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (ConnectException ce) {
            JOptionPane.showMessageDialog(null, "Server još uvek nije pokrenut.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška!", JOptionPane.ERROR_MESSAGE);
        }
        System.exit(0);
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
                                         
        try {
            if (Logovanje.getInstance().getUlogovaniKoordinator()== null) {
                toZahtev.setOperacija(Konstante.KRAJ_RADA);
                Komunikacija.getInstance().posalji(toZahtev);
                toOdgovor = Komunikacija.getInstance().procitaj();
                if (!toOdgovor.getPoruka().equals("")) {
                    JOptionPane.showMessageDialog(this, toOdgovor.getPoruka(), "Greška", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (ConnectException ce) {
            JOptionPane.showMessageDialog(null, "Server još uvek nije pokrenut.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jTextFieldSifraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSifraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSifraActionPerformed
    
           
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOtkazi;
    private javax.swing.JButton jButtonUlogujSe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldKorisnickoIme;
    private javax.swing.JPasswordField jTextFieldSifra;
    // End of variables declaration//GEN-END:variables

    
       private void pokreniAplikaciju() throws Exception {
        if (!proveraUnosa()) {
            return;
        }
        Koordinator r = new Koordinator();
        r.setKorisnickoIme(jTextFieldKorisnickoIme.getText().trim());
        r.setKorisnickaLozinka(jTextFieldSifra.getText().trim());

        TransferObject to = new TransferObject();
        to.setOperacija(Konstante.ULOGUJ_SE);
        to.setParametar(r);
        Komunikacija.getInstance().posalji(to);
        to = Komunikacija.getInstance().procitaj();
        if (!to.getPoruka().equals("")) {
            JOptionPane.showMessageDialog(this, to.getPoruka());
            return;
        } else {
            isprazniPolja();
        }
        r = (Koordinator) to.getOdgovor();
        Logovanje.getInstance().setUlogovaniKoordinator(r);

        this.dispose();
        new GlavnaForma().setVisible(true);
        JOptionPane.showMessageDialog(this, "Uspenšno ste se prijavili!", "Info", JOptionPane.INFORMATION_MESSAGE);
    }

    private void isprazniPolja() {
        jTextFieldKorisnickoIme.setText("");
        jTextFieldSifra.setText("");
    }

    private boolean proveraUnosa() {
        String korisnickoIme = jTextFieldKorisnickoIme.getText().trim();
        String lozinka = jTextFieldSifra.getText().trim();

        if (StringUtils.isEmptyOrWhitespaceOnly(korisnickoIme)) {
            jTextFieldKorisnickoIme.setText("Morate uneti korisničko ime!");
            return false;
        }
        if (StringUtils.isEmptyOrWhitespaceOnly(lozinka)) {
            jTextFieldSifra.setText("Morate uneti lozinku!");
            return false;
        } 
        return true;
    }
}
