/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.RadneSmene;
import domen.Zaposleni;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import konstante.Konstante;
import model.modelTabeleRadneSmene;
import transfer.TransferObject;

/**
 *
 * @author Vladan
 */
public class PregledSmenaPanel extends javax.swing.JPanel {
    private GlavnaForma glavna;
    TransferObject toZahtev = new TransferObject();
    TransferObject toOdgovor = new TransferObject();
    /**
     * Creates new form DodajNoviUgovorPanel1
     */
    public PregledSmenaPanel(GlavnaForma glavna) {
        initComponents();
        this.glavna = glavna;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Pretrazi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonIzmeni)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButtonIzmeni))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RadneSmene smena = new RadneSmene();
        int vreme = 0;
        try {
            vreme = Integer.parseInt(jTextField1.getText().trim());
        } catch (Exception e) {
        }
        smena.setVremeRadneSmene(vreme);
        Zaposleni z = new Zaposleni();
        z.setImeIPrezime(jTextField1.getText().trim());
        smena.setZaposleni(z);
        
        toZahtev.setOperacija(Konstante.VRATI_SMENE_PO_KRITERIJUMU);
        toZahtev.setParametar(smena);
        try {
            Komunikacija.getInstance().posalji(toZahtev);
            toOdgovor = Komunikacija.getInstance().procitaj();
        } catch (IOException ex) {
            Logger.getLogger(PregledSmenaPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PregledSmenaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(!toOdgovor.getPoruka().equals("")){
            JOptionPane.showMessageDialog(this, toOdgovor.getPoruka(),"Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        List<RadneSmene> lista = (List<RadneSmene>) toOdgovor.getOdgovor();
        if(lista.isEmpty()){
            modelTabeleRadneSmene model = new modelTabeleRadneSmene(lista);
            jTable1.setModel(model);
            JOptionPane.showMessageDialog(this, "Nije moguće pronaći radne smene po datom kriterijumu", "Neuspeh", JOptionPane.ERROR_MESSAGE);
            return;
        }
        modelTabeleRadneSmene model = new modelTabeleRadneSmene(lista);
            jTable1.setModel(model);
            JOptionPane.showMessageDialog(this, "Uspešno pronadjene smene!","Uspeh",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        // TODO add your handling code here:
        modelTabeleRadneSmene model = (modelTabeleRadneSmene) jTable1.getModel();
        int red = jTable1.getSelectedRow();
        if(red==-1){
            JOptionPane.showMessageDialog(this, "Selektujte odredjenu smenu","Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        RadneSmene smena = model.vratiSmenu(red);
        
        glavna.pozoviUpdateSmene(smena, glavna);
        
    }//GEN-LAST:event_jButtonIzmeniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables


    public void sredi() {
        toZahtev.setOperacija(Konstante.VRATI_RADNESMENE);
        try {
            Komunikacija.getInstance().posalji(toZahtev);
            toOdgovor = Komunikacija.getInstance().procitaj();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        if (!toOdgovor.getPoruka().equals("")) {
            JOptionPane.showMessageDialog(this, toOdgovor.getPoruka(), "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        List<RadneSmene> lista = (List<RadneSmene>)toOdgovor.getOdgovor();
        modelTabeleRadneSmene model = new modelTabeleRadneSmene(lista);
        jTable1.setModel(model);
    }
}
